### ISSUE TITLE
Should this be a subcommand?

### ISSUE THREAD

**Issue by jasonkarns** [nodenv/nodenv-package-json-engine#10]
I see that this plugin exposes a subcommand, thanks to the `bin/nodenv-*` executable. Is this intentional?  Is this something we expect end users will want to check? I can see the utility in being able to inspect the version that nodenv will pick up from the package.json (for debugging purposes), but there might be easier ways.

I can also see the desire to have it as a subcommand for parity. Presently, there exists `nodenv-shell`, `nodenv-local`, and `nodenv-global`. Each of these can be used as setters _or_ getters. For parity, I would recommend that this plugin expose a similarly named subcommand; perhaps `nodenv-package` or `nodenv-package-json` to be more similar in spirit to `shell`, `local`, and `global`. For parity, I would also hope the subcommand would function as a setter and actually write the given version to package.json. Additionally, I would hope it accepts a `--unset` flag to remove the engine specification from package.json. This would make the interface for the version selection match shell/local/global almost exactly.

And _if_ this plugin should be exposing a subcommand, I would suggest that it conform to the standard of other plugins. That is, offering tab completion, help/usage output, etc.

If it is _not_ desired that this plugin expose a subcommand, then I propose the current executable be moved out of `bin/` and into `libexec/` following the pattern of other plugins and nodenv itself.

If the vote is to retain the subcommand, I can open separate issues for the other features I mentioned so that their discussion doesn't happen here.

**Comment by hurrymaplelad** [comment]
Oh, interesting!  The implementation and tests for this plugin were cribbed heavily from (rbenv-bundler-ruby-version)[https://github.com/aripollak/rbenv-bundler-ruby-version], which put it's script in `/bin`.  

No strong feelings here. I'd go with whichever is less work, likely moving into `libexec/`, until there's a real need for a subcommand.  Work for you?
