### ISSUE TITLE
Not setting node w/ nodenv version 1.0.0

### ISSUE THREAD

**Issue by bgerstle** [nodenv/nodenv-package-json-engine#13]
On Mac OS X 10.11.4 (using a [Boxen](https://github.com/boxen/our-boxen) setup).  Tried installing manually via Homebrew and then again [via Boxen](https://github.com/bgerstle/my-boxen/commit/02dde413cb5bcc83eace9f1d181fde666896567e) with no luck.  Are there any logs I could look at?

**Comment by jasonkarns** [comment]
Hopefully a red herring, but your mentioning boxen has me afraid you may have the wrong version of nodenv. Boxen originally used https://github.com/wfarr/nodenv, not https://github.com/nodenv/nodenv. But assuming you do have https://github.com/nodenv/nodenv...

`nodenv version` will show the active node version and how it was set (via local file, global, or env var).

If you set `NODENV_DEBUG=1` while running any nodenv command, you'll also get full debug output.

Try `NODENV_DEBUG=1 nodenv version` and gist up the output.

**Comment by bgerstle** [comment]
Strange, it appears to be working now.  For posterity, my Boxen is running nodenv 1.0.0 from https://github.com/oinutter/nodenv.  The latest version of puppet-nodejs uses this version [by default](https://github.com/boxen/puppet-nodejs/blob/0e61a578de01f4260f2b81dcfcd85ef14b19ee41/manifests/nodenv.pp#L22), but it looks like there's already a [pull request](https://github.com/boxen/puppet-nodejs/pull/64) to point to the nodenv org version.  If I catch the issue again I'll re-open this w/ debug output.  Thanks for your help! ❤️

**Comment by jasonkarns** [comment]
Cool! And FYI, the nodenv org version and OiNutter's version are one and the same.

**Comment by bgerstle** [comment]
Figured as much, thanks for confirming!
