### ISSUE TITLE
Relative paths broken for Homebrew install

### ISSUE THREAD

**Issue by wmadden** [nodenv/nodenv-package-json-engine#21]
After installing with Homebrew I get this error:

```sh
› nodenv which node
/usr/local/bin/nodenv-package-json-engine: line 42: /usr/local/bin/../deps/semver.sh: No such file or directory
package-json-engine: no version satisfying `4.1.2' installed
```

It's correct, there are no dependencies available in `/usr/local`; that path is completely wrong. I don't know enough about how Homebrew packages are installed to correct it, but installing via git in the `$(nodenv root)` directory (the other listed installation method) works perfectly.

**Comment by jasonkarns** [comment]
Thanks for reporting. Will look into it.

**Comment by jasonkarns** [comment]
To be clear (for the broken installation), do you have both nodenv and the plugin installed via homebrew? (via the nodenv tap)

Or nodenv via homebrew and the plugin via git?

**Comment by wmadden** [comment]
Sorry for the delayed response; to be clear it's for both installed via Homebrew. As a workaround I installed `nodenv` using Homebrew and `nodenv-package-json-engine` via git and then it worked.

**Comment by jasonkarns** [comment]
Finally got the travis build working for nodenv homebrew tap (something is wrong with the osx image and ruby 2.0)

The tap is now updated and should install successfully. Please reopen if this is not the case.
