### ISSUE TITLE
Let NODENV_VERSION take precedence

### ISSUE THREAD

**Issue by novemberborn** [nodenv/nodenv-package-json-engine#23]
Like `.node-version`, it'd be useful if `NODENV_VERSION` could take precedence. I have a `package.json` which allows Node.js `>=4`. This plugin automatically selects the highest version I have installed, which makes it hard to test on older Node.js versions.

**Comment by jasonkarns** [comment]
Sounds good. Mind stabbing at a PR?

Just need a test and most likely the addition of a check for `nodenv shell` here (similar to existing check) https://github.com/nodenv/nodenv-package-json-engine/blob/master/bin/nodenv-package-json-engine#L47

**Comment by novemberborn** [comment]
Sure, just need to find some time 😄 

If anybody else wants to take this on be my guest.
