### ISSUE TITLE
`nodenv version-name` doesn't recognize this plugin

### ISSUE THREAD

**Issue by rmm5t** [nodenv/nodenv-package-json-engine#25]
**`package.json` has `engines.node` specified:**

```bash
$ cat package.json 
{
  "engines": {
    "node": "6.10.3",
    // ...
```

**`node -v` then behaves as expected:**

```bash
$ node -v
v6.10.3
```

**However, `node version` (and `node version-name`) do not behave as expected (they are returning my globally set version):**

```
$ nodenv version
8.9.4 (set by /Users/i2190/.nodenv/version)

$ nodenv version-name
8.9.4
```

**Comment by rmm5t** [comment]
I should also add some context as to why I care about this discrepancy.  I keep my current node version in my bash prompt at all times, and the prompt relies on `nodenv version-name`.

**Comment by hurrymaplelad** [comment]
Thanks for the heads up! PR with fix is up.
