### ISSUE TITLE
Matches babel env preset instead of engine

### ISSUE THREAD

**Issue by murkey** [nodenv/nodenv-package-json-engine#31]
Hello! I've found a bug. [The regex here](https://github.com/nodenv/nodenv-package-json-engine/blob/ba866158e57badffe9591f99bff327bf1cb514a0/libexec/nodenv-package-json-engine#L35) also matches [Babel preset options](https://babeljs.io/docs/plugins/preset-env/). I happen to be using the `"node": "current"` Babel env setting for a few projects, which causes the plugin to report ``package-json-engine: no version satisfying `current' installed``. Let me know if you're open to PRs, thanks!

**Comment by jasonkarns** [comment]
Yes, thank you! Though I am not excited to iterate on tests of the regex ;)

**Comment by murkey** [comment]
Are you open to pulling in `jq` as a dependency? The method in question could just do `jq .engines.node $package_json_path`

**Comment by murkey** [comment]
Thanks for the guidance, I'll look into JSON.sh when I get a chance!
