### ISSUE TITLE
support for iojs!

### ISSUE THREAD

**Issue by jasonkarns** [nodenv/nodenv-package-json-engine#4]
Would be awesome to also support iojs.
- [ ] extract version from iojs engine
- [ ] hit http://semver.io/iojs/resolve instead of semver.io/node
- [ ] select higher version between iojs and node if they are _both_ installed

**Comment by hurrymaplelad** [comment]
Yes please! PR welcome.  I do wonder how quickly we won't need this now that io and node have merged...

**Comment by jasonkarns** [comment]
Yeah, sorta like releasing a feature that's deprecated immediately... But I imagine there are some people and apps out there that still specify an iojs engine. lo-priority but should be fairly easy to implement. I might take a crack at it this weekend.

**Comment by hurrymaplelad** [comment]
![giphy](https://user-images.githubusercontent.com/1083040/36639487-a6a41aac-19c2-11e8-90c7-4f4b10dd4b5c.gif)

Died with #6.
